### ISSUE TITLE
 Criar imagem / logo para PortalBrasil.jus

### ISSUE THREAD

**Issue by ericof** [plonegovbr/plonegovbr.portal#10]
**Descreva a tarefa**

Imagem que substituirá a atual imagem da distribuição PortalBrasil.jus

- [ ] Dimensões: 2048 × 1536

**Comment by Analulopes** [comment]
Logotipo com fundo azul

![Image](https://github.com/plonegovbr/plonegovbr.portal/assets/112990983/ae6091f5-c914-427b-a9c8-5112f6cf8dd0)

**Comment by Analulopes** [comment]
VERSÃO ATUALIZADA

![Image](https://github.com/plonegovbr/plonegovbr.portal/assets/112990983/cca4c21f-8836-4234-97b9-5afc45bb055e)

**Comment by ericof** [comment]
@Analulopes, você consegue gerar:
- [ ] Imagem 16:9 em png
- [ ] Imagem 16:9 em svg
