### ISSUE TITLE
 Criar imagem / logo para PortalBrasil.leg

### ISSUE THREAD

**Issue by ericof** [plonegovbr/plonegovbr.portal#11]
**Descreva a tarefa**

Imagem que substituirá a atual imagem da distribuição PortalBrasil.leg

- [ ] Dimensões: 2048 × 1536

**Comment by Analulopes** [comment]
Logotipo com fundo azul

![Image](https://github.com/plonegovbr/plonegovbr.portal/assets/112990983/c43fa36a-94b4-4f43-9ff5-b389732b5bf0)

**Comment by Analulopes** [comment]
VERSÃO ATUALIZADA

![Image](https://github.com/plonegovbr/plonegovbr.portal/assets/112990983/e6791cc5-ce86-4d5e-8b7b-2de05bd3a611)

**Comment by ericof** [comment]
@Analulopes, você consegue gerar:
- [ ] Imagem 16:9 em png
- [ ] Imagem 16:9 em svg

**Comment by Analulopes** [comment]
![Logo portal brasil LEG](https://github.com/plonegovbr/plonegovbr.portal/assets/112990983/bc84ff96-dc4d-4a31-a751-3fa948065c5c)
![Logo portal brasil LEG](https://github.com/plonegovbr/plonegovbr.portal/assets/112990983/eb46f466-8363-44d5-8ab6-3d3e04516aaf)
