### ISSUE TITLE
Criar nova logo para o PortalBrasil

### ISSUE THREAD

**Issue by ericof** [plonegovbr/plonegovbr.portal#16]

**Comment by Analulopes** [comment]
![Image](https://github.com/plonegovbr/plonegovbr.portal/assets/112990983/8d627e1e-51f6-43f0-8026-9979fbe28980)

**Comment by Analulopes** [comment]
VERSÃO ATUALIZADA

![Image](https://github.com/plonegovbr/plonegovbr.portal/assets/112990983/7973a006-a5f9-436a-82aa-cffe4d0cecbc)

**Comment by ericof** [comment]
@Analulopes, você consegue gerar:
- [ ] Imagem 16:9 em png
- [ ] Imagem 16:9 em svg

**Comment by Analulopes** [comment]
![Logotipo Portal Brasil Final transparente ](https://github.com/plonegovbr/plonegovbr.portal/assets/112990983/dc8e4902-6308-457b-ab83-35808e967a1e)
![Logotipo Portal Brasil SGV](https://github.com/plonegovbr/plonegovbr.portal/assets/112990983/804d3cb1-d5d7-4c61-b3dd-9389f0b20114)
