### ISSUE TITLE
Adicionar instruções de instalação do portal-brasil

### ISSUE THREAD

**Issue by ericof** [plonegovbr/plonegovbr.portal#21]
**Resumo**
Editar o arquivo README.md do repositório [portal-brasil](https://github.com/plonegovbr/portal-brasil/) com instruções atualizadas de como realizar a instalação do ambiente

**Comment by thalessalvador** [comment]
Arquivo criado e validado

**Comment by thalessalvador** [comment]
Instruções criadas e validadas
