### ISSUE TITLE
Criar helm charts (Plone e PortalBrasil)

### ISSUE THREAD

**Issue by ericof** [plonegovbr/plonegovbr.portal#22]

**Comment by fabiorauber** [comment]
Implemented in https://github.com/plone/charts/commit/9a2ff3c5d74dd94d81f4d0f8a4890f521c8c70ec

**Comment by fabiorauber** [comment]
Instruções de instalação via Helm Chart:
https://github.com/plonegovbr/plonegovbr.portal/pull/33
