### ISSUE TITLE
Logos para o Footer

### ISSUE THREAD

**Issue by ericof** [plonegovbr/plonegovbr.portal#30]
**Descreva a tarefa**

Criar SVG com altura padrão de 60px (daí podemos reduzir via css) para:

- [ ] PortalBrasil
- [x] PortalBrasil.Edu
- [x] PortalBrasil.Gov
- [x] PortalBrasil.Jus
- [x] PortalBrasil.Leg

**Comment by Analulopes** [comment]
![Image](https://github.com/plonegovbr/plonegovbr.portal/assets/112990983/92f163b1-c773-42f8-bec3-8a6b7903b1d2)
![Image](https://github.com/plonegovbr/plonegovbr.portal/assets/112990983/b6c2db48-9892-4960-b28c-ce0df2e40e71)
