### ISSUE TITLE
Criar teste para post handler no portal_edu.

### ISSUE THREAD

**Issue by ramiroluz** [plonegovbr/plonegovbr.portal#35]
**Teste unitário para post_handler da distribuição portal_edu**

Implementar teste para o post_handler que inicialmente pode ser simples e verificar se existe registro no log de sucesso de execução.

**Comment by italo2sanfer** [comment]
O teste está sendo implementado no portal_edu.
Os testes a serem ajustados são:
- [ ] - O primeiro teste consiste em colocar uma logo no portal e verificar se tudo ocorreu corretamente.
- [ ] - O segundo teste consiste em verificar a saída do logging ao se colocar a logo no portal.

**Comment by italo2sanfer** [comment]
Os dois testes se transformaram em um único com dois asserts. Pois na verdade os dois testes são direcionados para a mesma função.

**Comment by italo2sanfer** [comment]
Teste reformulado. Inserido em test_site_creation.
