### ISSUE TITLE
Criar imagem / logo para PortalBrasil.edu

### ISSUE THREAD

**Issue by ericof** [plonegovbr/plonegovbr.portal#8]
**Descreva a tarefa**

Imagem que substituirá a atual imagem da distribuição [PortalBrasil.edu](https://github.com/plonegovbr/plonegovbr.portal_edu/blob/237bdbfb58da70ce428dbf662aea75ee7d1d9543/src/plonegovbr/portal_edu/distributions/portal_edu/image.png)

- [ ] Dimensões: 2048 × 1536

**Comment by Analulopes** [comment]
![Image](https://github.com/plonegovbr/plonegovbr.portal/assets/112990983/af53b0ac-f666-4607-8a50-35bf31e2026c)

**Comment by Analulopes** [comment]
![Image](https://github.com/plonegovbr/plonegovbr.portal/assets/112990983/732d88bd-b6b8-4d7f-b842-72d0056f0080)

**Comment by Analulopes** [comment]
Logotipo com fundo azul

![Image](https://github.com/plonegovbr/plonegovbr.portal/assets/112990983/bf31a0f0-b52f-41f9-b1ae-fe69ba645329)

**Comment by Analulopes** [comment]
VERSÃO ATUALIZADA 

![Logotipo Portal Brasil EDU-01](https://github.com/plonegovbr/plonegovbr.portal/assets/112990983/98817965-f122-4303-a502-62f9788de366)
